### PR TITLE
New setting: SHOW_FULL_ARTICLE

### PR DESCRIPTION
**Pull request by atodorov**
when set to True will show the full article content on index.html
instead of truncated summary.

### CODE REVIEW

**Comment by atodorov** [comment]
@gilsondev - do you mind merging this so I can add remaining documentation from the other commits. Here I've introduced the Other configuration section for everything else to go into.

**Comment by gilsondev** [comment]
Can I merge this PR?

**Comment by gilsondev** [comment]
You can create a new PR to update the documentation.

**Comment by atodorov** [comment]
Yes, please merge.

**Pull request merged**
