### PR TITLE
add classes to body tag

### PR DESCRIPTION
**Pull request by nerdoc**
depending on page or article slug, add page-%slug% or article-%slug% class to <body>

### CODE REVIEW

**Comment by gilsondev** [comment]
What is the purpose of this?

**Comment by nerdoc** [comment]
to add custom CSS only for a certain page:

    .page-team h2 {
        border: 1px solid lightgrey;
    }

This is a common practice for many CMS - and I was working often with this in Drupal, look at that.

**Comment by nerdoc** [comment]
I just saw that there are more possibilities -  not only page and article, but tag and category as well. If you like I would push more commits to the branch so you can sqash and add everything at once...

**Comment by gilsondev** [comment]
It's a good approach. I'll leave the PR open to be able to include more things related to this okay?

**Comment by nerdoc** [comment]
That's perfectly ok. give me a few days, I don't have too much time ATM.

**Comment by nerdoc** [comment]
Hi, I think the cleanest approach is this here. A one-liner gets to long.

**Pull request merged**
