### PR TITLE
add `HEADER_COLOR` option to render header with a simple color

### PR DESCRIPTION
**Pull request by drgarcia1986**

### CODE REVIEW

**Comment by diegogarcia-luizalabs** [comment]
@gilsondev you can review ?

**Comment by drgarcia1986** [comment]
@gilsondev you can review ?

**Comment by gilsondev** [comment]
Sure ;)

**Comment by guilhermetoti-luizalabs** [comment]
@drgarcia1986 awesome! I think it's a great new variation option for header! :+1:

**Comment by gilsondev** [comment]
Update the README.md with this modification please.

**Comment by drgarcia1986** [comment]
done :)

**Comment by drgarcia1986** [comment]
add commit https://github.com/drgarcia1986/pelican-clean-blog/commit/4818dbb5f77f4aeccee1edce5a4d0ff33a378c38 to fix some `README.md` issues

**Comment by gilsondev** [comment]
Thanks ;)

**Comment by drgarcia1986** [comment]
:smile:

**Pull request merged**
